### ISSUE TITLE
Can't install module abem on windows

### ISSUE THREAD

**Issue by Yulia444** [fjargsto/abem#13]

**Comment by fjargsto** [comment]
I've never tested this on Windows. What's the error you're getting? The latest code here is using Cython and a small C++ module. If you want to do a `python setup.py develop`, you'll need Visual C++ installed on your system.

**Comment by Yulia444** [comment]
after installing abem via pip this error occurs.
![error_abem](https://user-images.githubusercontent.com/39921230/83167294-b9feec00-a118-11ea-857a-101c7b82351b.png)

**Comment by fjargsto** [comment]
Ah, you're trying to use the PyPI package. I haven't updated this in a while and even if the requirements.txt were found, it wouldn't work under Windows. I also don't have time right now to update this to match what is in the repo right now. I would recommend you pull this GitHub repo and try installing from source. I updated this with a C++ implementation instead of C99 of the integral operators which at least makes this potentially work under Windows.

**Comment by fjargsto** [comment]
I did pushed some code this weekend fixing compilation issues on Windows. I also made new release packages and pushed them to PyPI. If you could, please give this a try and let me know if this resolves your problems. I did test installing/building from GitHub as well as installing with pip. When installing with pip, you need to have the dependencies: wheel, Cython, scipy, and numpy installed prior to installing abem.

**Comment by Yulia444** [comment]
It works. Thank you very much.
